### ISSUE TITLE
Query for anonymous types

### ISSUE THREAD

**Issue by IAmAgainst** [praeclarum/sqlite-net#1009]
It would be nice to be able to make queries without having to declare a class for every different query result type. Something like this:

`var users = con.Query<(int Id, string Username)>("Select Id, Username from...");`

which, by the way, does compile and run but returns the correct amount of rows with default values.

**Comment by XavierAP** [comment]
This is a duplicate of #1007

**Comment by IAmAgainst** [comment]
I apologize, I searched for "anonymous types" before asking the question and didn't find anything. Anyway, implementing this functionality for any amount of (SQL friendly) rows seems more practical than just tuples specifically as the other question suggests.

**Comment by XavierAP** [comment]
OK sorry for misunderstanding. :-)
Can you provide a code example of what you want? The code in your original post is using a ValueTuple (and will be solved by  #1012). What other kind of anonymous types would you like to work?
What is called specifically ["anonymous types"](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/anonymous-types) in .NET would be nice, but I don't think it can be done, because they're read-only, and they can't be declared as return or parameter types...

**Comment by IAmAgainst** [comment]
Perhaps I did't use the correct term, I'm talking about receiving the result of a query without having to declare a class which contains all the columns returned by the query. For example one can declare a list in the following way:

`
var test = new List<(string Name, int Id, int Score)>();

test.Add(("John Doe", 18, 1432));
`

Without having to declare a class and have a list of that class. I'd like to be able to provide the name and type of each column during the declaration of the variable instead of creating a new class every time I decide to modify a query. Just like I wrote in my first post, only that with any amount of columns. For example:

`var users = con.Query<(int Id, string Username, int Score)>("Select Id, Username, Score from...");`

Maybe I misunderstood what a tuple means, I thought a tuple was a set of two values but after your reply I searched it and it seems that it's any set of values so maybe the issue you mentioned is just what I was talking about.

**Comment by XavierAP** [comment]
Indeed what you are using in your code is a ValueTuple. Tuple sounds like duple buy they can have any number of members.
My PR will make it work, but it will be limited to 7 members (columns). This is because of a quirk in how Microsoft implements these ValueTuples, and the difficulty it creates for reflection. It's probably not impossible to support it, but it complicates the code a lot and the use case is likely not worth it.

**Comment by IAmAgainst** [comment]
Great, I'll look forward to it!
Happy coding..
