### ISSUE TITLE
Plans to support WAL (write-ahead logging)?

### ISSUE THREAD

**Issue by 1Cor125** [praeclarum/sqlite-net#341]
Are there any plans to support this feature available since sqlite 3.7? There are advantages to WAL in situations where there is a lot of contention between readers and writers. My other question is has this been investigated to see if it is as simple as adding the open flag to the enum or are there not-so-obvious code changes needed to implement WAL?

**Comment by pcolmer** [comment]
I'm interested in this as well but it does look like some code changes are required.

If you get a connection and then go:

DBConnection.Execute("PRAGMA journal_mode=WAL");

an exception gets thrown in ExecuteNonQuery() because the command results in SQLite returning SQLITE_ROW as the result code, which ExecuteNonQuery turns into an exception. The code needs to be modified to retrieve the row of output and, perhaps, do something with that. Unfortunately, I'm not a SQLite expert so this is only likely to be a partial answer :).

**Comment by pcolmer** [comment]
I've managed to "hack" ExecuteNonQuery in a way that allows the PRAGMA statement to execute but it really is a hack because I'm basically throwing away whatever gets returned. The issue here is that ExecuteNonQuery doesn't actually expect to get anything back, which is why the current code throws the exception.

So, if you aren't bothered about confirming that the journal mode has changed, this works but it really isn't ideal and there probably needs to be a *much* cleaner interface written to handle journal mode changes :)

        public int ExecuteNonQuery()
        {
            if (_conn.Trace)
            {
                Debug.WriteLine("Executing: " + this);
            }

            var r = SQLite3.Result.OK;
            var stmt = Prepare();
            do
            {
                r = SQLite3.Step(stmt);
                if (r == SQLite3.Result.Row)
                {
                    var colType = SQLite3.ColumnType(stmt, 0);
                    if (colType == SQLite3.ColType.Integer)
                    {
                        var result = ReadCol(stmt, 0, colType, typeof(int));
                        Debug.WriteLine($"Returned {result}");
                    }
                    else if (colType == SQLite3.ColType.Text)
                    {
                        var result = ReadCol(stmt, 0, colType, typeof(string));
                        Debug.WriteLine($"Returned {result}");
                    }
                }
            } while (r == SQLite3.Result.Row);
            Finalize(stmt);

            if (r == SQLite3.Result.Done)
            {
                int rowsAffected = SQLite3.Changes(_conn.Handle);
                return rowsAffected;
            }
            else if (r == SQLite3.Result.Error)
            {
                string msg = SQLite3.GetErrmsg(_conn.Handle);
                throw SQLiteException.New(r, msg);
            }
            else if (r == SQLite3.Result.Constraint)
            {
                if (SQLite3.ExtendedErrCode(_conn.Handle) == SQLite3.ExtendedResult.ConstraintNotNull)
                {
                    throw NotNullConstraintViolationException.New(r, SQLite3.GetErrmsg(_conn.Handle));
                }
            }

            throw SQLiteException.New(r, r.ToString());
        }

**Comment by paulanthonymorris** [comment]
That pragma statement returns a string so you need to use this:
conn.ExecuteScalar<string>("PRAGMA journal_mode=WAL");
That should work straightforwardly.

I have since learned since my post that this is all you really need to get
WAL working. The rest has to do with how you open connections once you are
in that mode. I would recommend following Android's pattern (or at least my
interpretation of their pattern from reading their source code) of one
read-write connection at any time on a database and as many concurrent
read-only connections as you want. Also don't switch threads on any
connection while it is in use. SQLite will know and it will throw.
Async/await can do this without your knowledge so be careful on that front.
I use only the synchronous API down low and if the transaction is long
enough to worry about blocking I use async/await up above in my service or
UI level.

Hth.

**Comment by pcolmer** [comment]
@paulanthonymorris Thank you! I did say I wasn't a SQLite expert so thank you for suggesting the better way of changing journal mode.

**Comment by praeclarum** [comment]
This has been worked on by @Clancey and I hope to get it in https://github.com/praeclarum/sqlite-net/pull/505

**Comment by praeclarum** [comment]
This is now enabled by default in 1.5.
