### ISSUE TITLE
please update to support SQLitePCL.raw 0.8.2 (package name has changed)

### ISSUE THREAD

**Issue by ps30** [praeclarum/sqlite-net#381]
Please update to support SQLitePCL.raw 0.8.2 - Note this package name has changed by the author and has dropped the _basic of the old package on Nuget.  SQLitePCL.raw 0.8.2 now includes the SQLite 3.8.11.1 binary.

**Comment by gerryhigh** [comment]
Echoing the same comment--see https://www.nuget.org/packages/SQLitePCL.raw_basic/ "Note that with the 0.8.0 release, the package ID is changing from 'SQLitePCL.raw_basic' to 'SQLitePCL.raw'. For now, the package exists under both IDs and they are identical. Eventually the old ID may stop getting "

For whatever reason today I'm unable to resolve the "basic"package.  If I update my packages.config to reference SQLitePCL.raw then I get a runtime error because SQLite-net can't find SQLitePC.raw_basic 0.7.1.0
