### ISSUE TITLE
Xamarin.iOS: Cannot update or delete records because table "has no PK"

### ISSUE THREAD

**Issue by jlovero** [praeclarum/sqlite-net#398]
I'm updating a Xamarin mobile app that was released over a year ago on iOS and Android.  In updating the Xamarin.iOS libraries, I noticed that updates and deletes of some SQLite records in our app stopped working.  I also have the most up-to-date version of the sqlite-net library.

In debugging the problem, I saw that failure to update/delete was accompanied by the message **"Cannot update/delete TableName: it has no PK"**.  Digging deeper, I found that the problem comes from the [TableMapping constructor](https://github.com/praeclarum/sqlite-net/blob/master/src/SQLite.cs#L1762).  Specifically, on [line 1789](https://github.com/praeclarum/sqlite-net/blob/master/src/SQLite.cs#L1789) my primary key property is NOT added to the list of columns because the `CanWrite` property is somehow false, even though the property has a public setter.  Since my Primary Key field is not being added to the mapping, I get the **"it has no PK"** error since SQLite cannot determine what the PK is to use for the updates/deletes.  Oddly enough, Inserts work just fine.

Xamarin on iOS is using Mono, so the `Type` objects are actually `MonoType` objects and the `!USE_NEW_REFLECTION_API` code paths are being followed.  I believe this might be a Reflection bug in Mono running on iOS.  I created a dotNetFiddle to show that the same code works when using the .NET Runtime: https://dotnetfiddle.net/FqwCYS.  The ID property that has the `[PrimaryKey]` attribute is writable (i.e. `p.CanWrite == true`) on .NET whereas it is not running on Xamarin.iOS.  The `MyCardStorageObject` used in that example is pulled directly from our codebase.  It is one of the types that is failing to update/delete.  There are several other types that are being saved to SQLite and they all have the same issue.  They are also all defining the ID Primary Key in the same way:

```csharp
[PrimaryKey, AutoIncrement, Column("_id")]
public int Id { get; set; }
```

I'm not expecting anyone here to be able to fix a reflection bug in Mono, but this is a nasty problem for my project and any idea for workarounds would be greatly appreciated.

**Comment by bobbyg603** [comment]
+1. Did you ever resolve this?

**Comment by jlovero** [comment]
I can't say that I solved it in the sense of understanding the root cause and fixing it.  Rather, I stumbled onto a solution when I changed the Linker behavior on my Xamarin iOS project.  It's been a rather long time, so I don't recall the exact details, but I believe my linker behavior was set to "Link all assemblies".  Per the [Xamarin documentation](https://developer.xamarin.com/guides/ios/advanced_topics/linker/#Link_all_assemblies): 

>When linking everything, the linker can use the whole set of its optimizations to make the application as small as possible. It will modify user code, which may break whenever the code uses features in a way that the linker's static analysis cannot detect.

It's a good bet that the linker optimized the code when I was using the `Link all assemblies` option in such a way that this bug was created.  If you are having this problem, see if the `Link SDK assemblies only` or `Don't Link` settings solves the issue.

**Comment by sonscode** [comment]
I have been stocked for a week now on this problem and even the above solution is not working for me... I think that the Id does not increments automatically, that's why it says :cannot update ... What actually works for me is incrementing the PK (Id) manually...as follows.

``persons.Id++`;`
At the moment of verifying and inserting data into the database, I just added the above code and it updated successfully.

private async void Register_Student(object sender, EventArgs e){... ... 

if(!string.Equals(newPassword.Text, rePassword.Text)){ 

warningLabel.Text = "Enter same pwd"; ... 
}
else{ 

    persons.Id++; //solution that worked for me at insertion level
    persons.UserName = newUsername.Text; //Text entered by the user
    }...
} 
Thanks...

**Comment by sonscode** [comment]
I have been stocked for a week now on this problem and even the above solution is not working for me... I think that the Id does not increments automatically, that's why it says :cannot update ... What actually works for me is incrementing the PK (Id) manually...as follows.

`persons.Id++;`
At the moment of verifying and inserting data into the database, I just added the above code and it updated successfully.
```

private async void Register_Student(object sender, EventArgs e){... ... 

if(!string.Equals(newPassword.Text, rePassword.Text)){ 

warningLabel.Text = "Enter same pwd"; ... 
}
else{ 

    persons.Id++; //solution that worked for me at insertion level
    persons.UserName = newUsername.Text; //Text entered by the user
    }...
} 
```
Thanks...
