### ISSUE TITLE
Does this support in-memory database?

### ISSUE THREAD

**Issue by chinhodado** [praeclarum/sqlite-net#403]
I got `SQLite.SQLiteException` when I tried `var db = new SQLiteConnection("Data Source=:memory:");`

**Comment by nurchi** [comment]
I wish it did. Or at least I wish it supported a stream vs an actual file name... Then you could easily create a `MemoryStream` object and use that as your in-memory database. Maybe with some hacking it could to that ;)

**Comment by steveloft** [comment]
I'm using it for an in-memory database. This works fine for me:

var db = new SQLiteConnection(":memory:");

**Comment by SlyNet** [comment]
It says that `SQLiteConnection` has no constructor with 1 argument

**Comment by steveloft** [comment]
https://github.com/praeclarum/sqlite-net/blob/master/src/SQLite.cs

Line 180 (the second parameter is optional)

**Comment by DOliana** [comment]
Would it be possible to have this in the portable library? This would be great for Testing.

**Comment by mkonstapel** [comment]
Is it possible to open _multiple_ connections to an in-memory DB? According to https://www.sqlite.org/inmemorydb.html, the connection string should be either
`"file::memory:?cache=shared"` for a single in-memory database or `"file:memdb1?mode=memory&cache=shared"` for one or more named in-memory databases.

However, the first throws an exception:
```
SQLiteException: Could not open database file: file::memory:?cache=shared (CannotOpen)
```

and the second creates a file-based db in a file called `file`. This is apparently taken from the URI, because it creates a file called `foo` if I change it to `"foo:memdb1?mode=memory&cache=shared"`.

**Comment by praeclarum** [comment]
As you noted, the lib uses `sqlite3_open_v2`.

@mkonstapel The lib version with iOS isn't always up to date. I added a `LibVersionNumber` property so you can inspect it. I wonder if that's what's causing you trouble?

**Comment by bill2004158** [comment]
@praeclarum 

`var db = new SQLiteConnection(":memory:");`
works,
however,
`var db = new SQLiteConnection("file::memory:?cache=shared");`
throw exception:

> SQLiteException: Could not open database file: file::memory:?cache=shared (CannotOpen)

**Comment by bill2004158** [comment]
does is because shared-cache is disabled by default?
http://www.sqlite.org/sharedcache.html
> SQLite includes a special "shared-cache" mode (disabled by default) intended for use in embedded servers

**Comment by bill2004158** [comment]
@praeclarum what is the api to enable shared-cache?

**Comment by picolino** [comment]
@bill2004158 Hello from 2020, I think this can help
``` csharp
new SQLiteConnection(":memory:", SQLiteOpenFlags.ReadWrite | SQLiteOpenFlags.SharedCache)
```

**Comment by picolino** [comment]
@praeclarum I think this issue must be re-opened because there is no possibility to open many connections to one in-memory database. We can't open connection to existing in-memory database because it seems like this library doesn't support [URI filename](https://www.sqlite.org/uri.html) connections strings.

I tried to use this code to open 2 connections to one in-memory database:
``` cs
new SQLiteConnectionString(":memory:", SQLiteOpenFlags.ReadWrite | SQLiteOpenFlags.SharedCache, false);
```
But it's not working at all.

Need to URI filename support.

**Comment by nbevans** [comment]
Have you tried adding SQLiteOpenFlags.Create (and ReadWrite and SharedCache) to your flags? When I did that, it started working.

**Comment by JGKL** [comment]
@nbevans could you provide your code? I agree with @picolino that this does not seem to work.

**Comment by paul-kiar** [comment]
According to the Sqlite documentation.  A filename of `:memory:` does not support shared cache flag.  We need a way to set the `mode=memory` in SQLiteConnectionString.  That would allow us to open a named in memory database with shared cache.  https://www.sqlite.org/inmemorydb.html

**Comment by paul-kiar** [comment]
The work around:
`        public const SQLite.SQLiteOpenFlags DefaultFlags =
                    // open the database in memory
                    (SQLiteOpenFlags)0x00000080 | 
                    // open the database in read/write mode
                    SQLite.SQLiteOpenFlags.ReadWrite |
                    // create the database if it doesn't exist
                    SQLite.SQLiteOpenFlags.Create |
                    // enable multi-threaded database access
                    SQLite.SQLiteOpenFlags.SharedCache;`
