### ISSUE TITLE
Guid Problem

### ISSUE THREAD

**Issue by lima66** [praeclarum/sqlite-net#412]
hi,

Guid are saved in string format(74c75369-760d-4116-bfc2-0f93cbea4cf0) and not in format (X'2605A2007C1A3242BD45105D8CA5D961'). This generates exception when download 
sqlite generate from server.

**Comment by praeclarum** [comment]
The choice was made to store the textual representation instead of the byte representation. This is generally the preferred method with sqlite databases: https://stackoverflow.com/questions/11337324/how-to-efficient-insert-and-fetch-uuid-in-core-data/11337522#11337522

You will need to use `byte[]` columns instead of guids if you have no control of the database schema.
