### ISSUE TITLE
Unable to call Config (ConfigOption.Serialized) when using USE_SQLITEPCL_RAW

### ISSUE THREAD

**Issue by vurtigo** [praeclarum/sqlite-net#444]
I've found SQLite prefers to be run in serialized mode on Android - since the change to bundle_green the options to Shutdown/Config & Initialize are commented out by compiler directives so I can't make the config change.

It looks like bundle_green may not support those calls?

**Comment by ericsink** [comment]
Apparently sqlite3_config never got implemented in SQLitePCLRaw.  I've logged a bug over in that project to fix it.  After that, sqlite-net will need a small tweak to expose the API upward.

**Comment by vurtigo** [comment]
that would be great. I just rolled the update out to the iOS side of the project and my background sync routine started SIGSEGV almost immediately. Rolling it back to a pcl that can set the Serialized option has it running fine again. 

Interestingly the droid was running well with the serialization setting - even though I originally implemented it there to fix a similar issue

**Comment by ericsink** [comment]
This can depend on whether the underlying sqlite library was compiled with the threading mode set to serialized or not.

For iOS, bundle_green uses the sqlite library that is part of iOS itself, and that library is (apparently) not compiled with serialized as the threading mode.

For Android, bundle_green includes a different instance of the sqlite library, instead of using the one from Android, since Android N doesn't allow that anymore.  This bundled instance is compiled with serialized threading mode.

**Comment by vurtigo** [comment]
I thought as much as I was researching yesterday

Is the iOS library compiled with support to change the threading mode? I gathered that it's possible to complie the sqlite library without support to change that. Hoping it's not the case with the iOS library

**Comment by bartdkmediahuis** [comment]
Any news on this one ?
Is there any other option we could set the serialization mode ?

**Comment by ericsink** [comment]
See ericsink/SQLitePCL.raw#106

In short, sqlite3_config got implemented, but now there is another problem preventing it from being used, but that problem has a workaround, which is to do sqlite3_shutdown() first.

**Comment by ericsink** [comment]
SQLitePCL.raw 1.1.1 addresses this problem.

**Comment by praeclarum** [comment]
Sounds like there is a solution.
