### ISSUE TITLE
Getting connection throws exception on iOS 6 / 7

### ISSUE THREAD

**Issue by RyanBuzzInteractive** [praeclarum/sqlite-net#446]
I am using MvvmCross and since the upgrade to this sqlite package I am getting an exception when trying to get a connection to the database on iOS 6.

I raised an issue there (https://github.com/MvvmCross/MvvmCross-Plugins/issues/133) and was pointed here as they just wrap this plugin apparently.  

I understand this is an old OS but I was wondering if there was any way to get it running as our client insists we support iOS 6. I have attached the exception log.

Exception log:
[sqlite.error.txt](https://github.com/praeclarum/sqlite-net/files/461558/sqlite.error.txt)

**Comment by RyanBuzzInteractive** [comment]
This is the method I am calling which is wrapping your code I believe:

`public SQLiteConnection GetConnection(string databaseName, bool prefixPlatformPath = true)
        {
            var config = new SqLiteConfig(databaseName);
            var databasePath = GetConnectionString(config, prefixPlatformPath);

            return new SQLiteConnection(databasePath, config.OpenFlags, config.StoreDateTimeAsTicks);
        }`

**Comment by RyanBuzzInteractive** [comment]
I think it might be because apparently sqlite3_close_v2 was only added in sqlite 3.7.14 and iOS 6 runs 3.7.13

ref: 
http://stackoverflow.com/questions/14288128/what-version-of-sqlite-does-ios-provide
aspnet/EntityFramework#3870

**Comment by ericsink** [comment]
Yep.  That's what I was guessing as well.

If this were to be fixed in the sqlite-net code itself, we could change that call to sqlite3_close().

An alternative would be to use a bundled SQLite library instead of the one provided by iOS.  But the PCL form of sqlite-net is configured to use SQLitePCL.bundle_green, which is a packaging that specifically prefers the use of the iOS system sqlite.

Changing either of the above would be @praeclarum 's decision.

BTW, another problem with bundling a SQLite is that SQLitePCL.raw (the package I maintain, and which is a dependency of sqlite-net-pcl) bundles iOS libraries which are not built for compatibility with iOS 6.  But I could probably fix that.

Anyway, if I fixed that issue, one option would be for you to include the sqlite-net source code yourself (instead of using the PCL nuget package), compile it for SQLitePCL.raw, and add the appropriate nuget packages for bundling a SQLite (which I can explain how to do if you chose that path).

**Comment by RyanBuzzInteractive** [comment]
Thanks dude, that's been a great help :)

**Comment by RyanBuzzInteractive** [comment]
Hey guys - I got my hands on an iPhone 4 today running iOS 7 and i'm getting the same problem :/ I will try a separate test project to check it's nothing else causing it, but it is fine on iOS 8 and 9. Very strange. I am guessing that you would consider iOS 7 support still kind of relevant? (genuine question)

**Comment by RyanBuzzInteractive** [comment]
I upgraded XCode and Xamarin and the crash seemed to disappear. I'll close this, Cheers for all the help.
