### ISSUE TITLE
Unable to load DLL 'sqlite3'

### ISSUE THREAD

**Issue by MelbourneDeveloper** [praeclarum/sqlite-net#448]
Full exception:
Unable to load DLL 'sqlite3': This operation is only valid in the context of an app container. (Exception from HRESULT: 0x8007109A)

All I want to know is, when the app runs, where is it looking for the SQLite dll? And, does it need some other file to run?

I've managed to get this working on UWP (God knows how I pulled that off in hindsight), but every time I go to a new platform I get stung by this. Right now, I'm trying to get it working in .NET 4.6.2. I've tried dumping the sqlite3.dll directly in the bin folder, but no luck. I just want to clear up the voodoo of how it is that .NET, or Mono, or whatever finds the DLL.

This thread has some advice but none of it works for me:
http://stackoverflow.com/questions/4744293/unable-to-load-dll-sqlite3-the-specified-module-could-not-be-found-exceptio

**Comment by ericsink** [comment]
From what you've said, I'm guessing you are not using the sqlite-net-pcl nuget package, right?

If you were, then the finding of sqlite3.dll is up to SQLitePCL.raw, which I know a thing or two about.

But if I'm right, and you are using sqlite-net in some other way (like, you are including the source code, or using the non-PCL nuget package, etc), then, er, I don't really know.  But I assume it does something really simple, like "just pinvoke whatever sqlite3.dll is found first in the PATH".

BTW, the error message you're getting is weird.  I haven't seen that one before.  Which piques my curiosity a bit.

And yes, sometimes the sqlite3.dll file needs to load the C runtime lib DLL as well, which causes the DLL load to fail.  But when that happens, the error message is usually different.  And I don't have enough details about your context to say whether that is happening in your case.  My conjecture is "no", that's not the issue.

Sorry for the likely-useless reply.

**Comment by MelbourneDeveloper** [comment]
No. Thanks heaps for the reply!

> I'm guessing you are not using the sqlite-net-pcl nuget package, right?

No. In the past, I have taken the sqlite-net-pcl repo, and hacked the PCL library to work on UWP. I actually got that working, but I have no idea how I got it working.

> If you were, then the finding of sqlite3.dll is up to SQLitePCL.raw, which I know a thing or two about.

Sounds intriguing. Tell me more about this SQLitePCL.raw that you speak of...

> But if I'm right, and you are using sqlite-net in some other way (like, you are including the source code, or using the non-PCL nuget package, etc), then, er, I don't really know. But I assume it does something really simple, like "just pinvoke whatever sqlite3.dll is found first in the PATH".

In this case, I added the sqlite-net package for .NET. All it did was add the two source code files to my project. Actually, that's probably what I want. Perhaps there's some problem with my understanding of pinvoke. I added "[...]sqlite-net\lib\metro\x86" to my path, but the problem persists...

> BTW, the error message you're getting is weird. I haven't seen that one before. Which piques my curiosity a bit.

I get it all the time, in sqlite-net-pcl and sqlite-net. Others get it too:
http://stackoverflow.com/questions/4744293/unable-to-load-dll-sqlite3-the-specified-module-could-not-be-found-exceptio

> And yes, sometimes the sqlite3.dll file needs to load the C runtime lib DLL as well, which causes the DLL load to fail.

This is the crux of the voodoo for me. How does this work on all the different platforms?

**Comment by MelbourneDeveloper** [comment]
I uninstalled sqlite-net and installed sqlite-net-pcl, and now it works. I'm still left in the dark as to why.

**Comment by ericsink** [comment]
The "This operation is only valid in the context of an app container." error message is the weird one.  It makes me wonder about things like trying to use a WinRT version of sqlite when you're in a regular sort of app.

The error message in the stack overflow post you linked, "The specified module could not be found", is the much more common situation.  I see that one all the time.  Your situation appears to be different.

SQLitePCL.raw is a library I maintain which does nothing but try to handle all this voodoo across all kinds of platforms.  It does not present a friendly API to be used when writing an app.  Rather, it stays low level, and is designed to be used underneath something like sqlite-net.  It is used by several different higher level libraries.

Originally, sqlite-net simply did its own pinvoke calls to load the sqlite3 DLL.  Many folks still use it that way, but the more platforms you need, the more painful this gets.

But when you use sqlite-net-pcl (the nuget package containing the PCL form of sqlite-net), it brings in SQLitePCL.raw as a dependency, which handles all the ridiculous, arcane details of calling SQLite from .NET on lots of different platforms.

I don't mean to duck your question "How does this work on all the different platforms?", but, well, it's a very complex topic.  That's why SQLitePCL.raw exists.

**Comment by ericsink** [comment]
Bottom line:  My best guess is that whatever you did to get things working on UWP resulted in a SQLite lib that is not compatible with a plain old net46 app, but you tried to use it that way, and pinvoke complained.  But that's just a guess.
