### ISSUE TITLE
Add support to set SQLite3Provider

### ISSUE THREAD

**Issue by lummoj** [praeclarum/sqlite-net#476]
Is it possible to add support for choosing or manually setting the SQLite.raw provider? Rather than always calling SQLitePCL.Batteries.Init() in the SQLiteConnection static constructor.

As it stands I'm not able to use the sqlite-net-pcl NuGet package on a Raspberry Pi 3 using Mono out of the box as it requires a 32-bit Linux binary. 

It works fine if I symbolically link libsqlite3.so to libe_sqlite3.so but what I'd really like to do is just use the SQLite3Provider_sqlite3 provider rather than SQLite3Provider_e_sqlite3 provider but this doesn't seem possible in the current version.

Perhaps the SQLiteConnection could lazy initialize in the dynamic constructor with an additional constructor allowing the ISQLite3Provider to be passed in? I'm happy to make this change if you're interested.

**Comment by lummoj** [comment]
I should also note the other benefit of this approach would be to allow usage of SQLCipher which would be useful

**Comment by ericsink** [comment]
1.  Calling SetProvider() or Batteries.Init() in the dynamic constructor would be troublesome, because then it will be called every time a connection is opened, which would cause problems for apps that open/close multiple connections frequently.  The Init() call really wants to only be done at init time.

2.  That said, you could override the Batteries.Init() call by just making another call to SetProvider.  Last call wins.

3.  I wonder if I should include a 32-bit Linux binary of e_sqlite3.

4.  As with the majority of packages that embed SQLitePCL.raw, the owner of sqlite-net-pcl (which is @praeclarum, not me) prefers to make the Init() call so that users don't have to do it.  A more-flexible but less-friendly approach would be to simply take the dep on SQLitePCLRaw.Core and make the app do the Init() call.  But that would cause trouble (and therefore user questions) in the most common case.

5.  If probably ought to fix and re-submit PR #457.  I added SQLitePCL.Batteries_V2.Init() to support the ability to bait-and-switch the Init() call from one bundle type to another.  This would be of some help in your situation (and in your mention of using SQLCipher).

**Comment by lummoj** [comment]
Thanks for the feedback Eric, I'll address your comments below:

1. I think in this scenario it would be something along the lines of :
`static bool _initialised = false;`
`SQLiteConnection(string databasePath, ISQLiteProvider provider = null)
{
if(!_initialised) 
{
if(provider == null)
{
Batteries.Init();
}
else
{
SetProvider(provider)
}
_initialised = true
}
}`
which should make the overhead relatively minimal. The downside is that each time you make the connection you'd have to pass in the provider and I'm not sure what the behaviour should be if the provider changes at some point which is probably where this idea breaks down. A new provider would have to be ignored (as above) as it would break any existing connections but this not particularly intuitive.

2. In the 32-bit Linux scenario you get an exception when constructing SQLiteConnection for the first time (it is called in the static constructor) due to the missing e_sqlite3 library so there's no opportunity to call SetProvider afterwards unless you catch, SetProvider and construct again.

3. This would certainly solve the particular issue that I encountered but I think changing providers or batteries is the way to go in a more general sense.

4. This definitely makes sense and I certainly agree with that approach. I think changing the provider should be the exception not the rule.

5. This would help especially as you already have an SQLCipher bundle but I think there is still a use case for other configurations such as using the operating system libraries.

**Comment by praeclarum** [comment]
Overall I like the idea of making the provider first class and controllable; however a few things worry me.

Can you describe why Linux is so broken in your point 2? I don't understand the problem or the solution.

And the obvious question I have to ask myself and you guys is that if we have an ISQLiteProvider, why don't we just make that an instance of the connection and allow different connections to use different providers? (This is a big change, just want to make sure it gets put out there.)

Can you also tell me how exactly one would integrate SQLCipher into an app? Which packages would you include, and what init calls do you need in the ctor to make it work?

**Comment by ericsink** [comment]
> Can you describe why Linux is so broken in your point 2? I don't understand the problem or the solution.

One issue here is that my "batteries included" bundle packages do not have support for 32-bit Linux.

Also involved in this thread is that sqlite-net-pcl takes it dependency on bundle_green, which (1) makes things easier in most cases, and (2) makes things a bit harder if bundle_green is not what you want.

The "solution" I mentioned is to (1) force sqlite-net-pcl make its static constructor call to Batteries.Init(), (2) catch the exception that will be thrown, and (3) call raw.SetProvider() to install the desired provider.  I admit this is ugly.

The solution mentioned by OP is to move the init call from the static constructor to the dynamic constructor.  I'm not a big fan of this approach in general.

> why don't we just make that an instance of the connection and allow different connections to use different providers

That's something I should think more about.  But as you say, it would be a big change.  SQLitePCL.raw is currently very much designed around the idea that there is one provider, static, initialized once-ish.

My off-the-cuff reaction is that I'm not sure there is a use case for wanting multiple connections to use different providers.  Also, if somebody did this on a Unix-ish system and accessed the same file from different providers, they could corrupt their data.

Anyway...

> Can you also tell me how exactly one would integrate SQLCipher into an app? Which packages would you include, and what init calls do you need in the ctor to make it work?

Using SQLCipher with SQLitePCL.raw is simply a matter of using bundle_sqlcipher instead of bundle_green.

(Well, to actually *use* the crypto features of SQLCipher, it is necessary to do a SQLite #pragma to set the encryption key.  But that could be done without any other changes to SQLite-net.)

Anyway, this is the tradeoff when taking a dependency on bundle_green and making the Batteries.Init() call from SQLite-net.  The nice thing is that most users don't have to make that Batteries.Init() call and it "just works".  The bad thing is that people who want anything other than bundle_green have a trickier problem.

And, to some extent, this is what Batteries_V2.Init() is trying to address (which was my not-quite-right PR #457 ).  Batteries_V2.Init() works exactly like the original, except that it allows one bundle to be swapped for another.  It can "bait and switch" across bundle types.  So, using SQLCipher is easy, and OP's problem could be addressed by substituting a custom bundle.

(Batteries_V2.Init() simply always lives in an assembly that has the same name regardless of what kind of bundle it is.  So it can be bait-and-switched by providing another assembly of that name containing the same call.  With the original Batteries.Init(), each bundle had the call in an assembly with a different name.  I think of this as a design mistake on my part, but fixing it would be a breaking change, so I just added a V2 version.)

**Comment by praeclarum** [comment]
OK sounds like I need to get that PR through. Thanks as always for the detailed explanation @ericsink!

Would it make sense to make another sqlite-net PCL that has the minimal reference and would require the user to select the provider bundle? We could name it something cool like `sqlite-net-pcl-i-know-what-im-doing`.

But it sounds to me like your V2 is a pretty good solution (it's an edge case right?) as long as I put a doc somewhere at the top of the README.

**Comment by ericsink** [comment]
There *are* some weird cases where it might be nice to have something like `sqlite-net-pcl-with-core-only`, but I also worry that it would add confusion to have yet another SQLite-net package.  I am inclined to say let's not create that package until we are sure we need it.  Batteries_V2 will get us out of most any situation.

**Comment by ndastur** [comment]
Can I just check, does the thread above mean that SqlCipher can't presently be used with sqlite.net-pcl?? It's just that the front page wiki makes it look like it as easy as adding the SQLitePCLRaw.bundle_sqlcipher package.
Thanks

**Comment by ericsink** [comment]
https://github.com/ericsink/SQLitePCL.raw/wiki/How-to-use-SQLCipher-with-SQLite-net

**Comment by ndastur** [comment]
Thanks @ericsink 
I know the clue may very well be in the name, but does that mean sqlite.net-pcl can't be added to a shared project?

**Comment by ericsink** [comment]
Just to be clear, you mean a shared code project, with a .shproj?  No, those kinds of project can't handle nuget packages.

**Comment by ndastur** [comment]
No. I have .csproj files in each platform's folder

Created using Xamarin Studio
File -> New Solution
Forms App
and then in the shared Code section selected Use Shared Library (i.e. NOT use Portable Class Library)

**Comment by ericsink** [comment]
Right.  That means you're using a .shproj (like said, not a portable class library).  Which means you can't use a nuget package in there, because a .shproj can't do nuget packages.

**Comment by ndastur** [comment]
Thank you. I might keep comments to #503 now as they seem to be merging

**Comment by praeclarum** [comment]
This is completed by the creation of the `sqlite-net-base` nuget package.
