### ISSUE TITLE
SQLiteConnection.Trace = true not working

### ISSUE THREAD

**Issue by xleon** [praeclarum/sqlite-net#485]
_defaultDatabaseConnection = new SQLiteConnection(path) { Trace = true };

I can´t see any trace on the application output.
Version 1.2.0 (iOS)

**Comment by JKennedy24** [comment]
I am also seeing this problem. Is there anything else I need to do to get trace working?

**Comment by bartdkmediahuis** [comment]
The problem with the current tracing statements is that they are using Debug.WriteLine (which are compiled out of the assembly in release mode). Is it ok for you @praeclarum to change them into Trace.WriteLine ? Since the default value of the Trace property is False, this will have no impact to users not using the Trace flag.
But with the current Nuget we are unable to use tracing. Only option is to compile a dll in debug mode.

**Comment by praeclarum** [comment]
This was fixed by adding https://github.com/praeclarum/sqlite-net/commit/c95cca09436524ed95ef220df13febd4f11989b7:

```csharp
public Action<string> Tracer { get; set; }
```

to the connection. Now you can do:

```csharp
connection.Tracer = Console.WriteLine;
```
