### ISSUE TITLE
Installation of other libraries with 1.3.1 Update?

### ISSUE THREAD

**Issue by rikrok** [praeclarum/sqlite-net#511]
Hey, so i'm not too sure if this is an issue as I'm new to Nuget and PCL methodology. 

When I update to 1.3.1 from 1.2.1, I have to agree to some various licenses from Microsoft. That's okay, but then I have to upgrade them. Then they show up in the install NuGet section. I feel that this is kind of bizarre and I can't really find any explanation of what is happening. 

Shouldn't the .NET reference in the Xamarin.Forms be sufficient for SQLite? Why did we get System.Collections and etc in this update? Will this cause bloat?

**Comment by ericsink** [comment]
This started happening with the addition of netstandard 1.1 support in the nupkg.

Basically, what I *think* is happening is that your tooling is looking at the nupkg and seeing two choices, one of which is a PCL profile, and the other is netstandard1.1.  It is choosing the latter.

And for netstandard1.1, the nupkg specifies a dependency group containing NetStandard.Library 1.6.0.  I *think* this is the correct thing to do, although I have sometimes wished I could find clearer guidance on whether to take a dep on NetStandard.Library or not.  But anyway...

The purpose of NetStandard.Library is to bring in all the dependencies your platform might need.  But most of them are going to end up being type-forwarded assemblies that have no actual impact on the output of your build process.

I *think* what you are seeing is harmless.  It should cause no bloat.  If you were using project.json instead of packages.config, or the new csproj stuff in VS 2017 and its ilk, then you would be less likely to notice this.

I also think the symptom could probably be eliminated by adding another dependency group for the TFM that matches the PCL profile in lib/ and excluding NetStandard.Library from that dependency group.

Cc @onovotny so he can (if he wants) correct me where I am not being correct.

**Comment by onovotny** [comment]
They are mostly empty type forwarders as @ericsink said, there shouldn't really be any bloat. I would suggest using either `csproj` + `project.json` or better yet `PackageReference` for your dependencies and get transitive behavior. Then you won't have to deal with the whole graph.

**Comment by dpedrinha** [comment]
I'm having this issue but it's installing those bloat sometimes only in droid projects, other times in both droid and ios, but not PCL and UWP projects. Into which projects are those supposed to be installed?

Any way, that doesn't feel right. It's more than 40 new packages. I'm keeping version 1.2.1.

**Comment by jcmanke** [comment]
It's an issue somewhere in how the dependencies are set up in the nuspec files. Compare to something like Newtonsoft.Json, which also targets both PCL Profile 259 and .NET Standard without getting confused and adding extra dependencies to the PCL projects.

**Comment by praeclarum** [comment]
This has been recently fixed in v1.4. Sorry for the trouble!

https://github.com/praeclarum/sqlite-net/commit/27fa298eedea925a8597a067414aeae7e4023ba1
