### ISSUE TITLE
Sharerable Sqlite DB within the network.

### ISSUE THREAD

**Issue by imZEH** [praeclarum/sqlite-net#516]
Can sqlite-net initiate connection to share sqlite database within the network ? I was trying to implement two machine share one sqlite database within the network. Would that be possible ?

Thank You.

**Comment by praeclarum** [comment]
Technically you could put the database on a share and access it from multiple processes but this isn't recommended.

You may enjoy this stack overflow response: https://stackoverflow.com/a/27457688/338

**Comment by Slodin** [comment]
I  use EmbedIO for this. This is not a solution only for SQLite, so it's not really a sqlite question/solution. However, what I have done is create a localhost server so other devices can call the exposed API url for get, post, and other methods. Although I could only test with localhost (127.0.0.1) because I don't have enough devices, but I'm assuming the API can be called by other devices on the same area network. At least that's what I'm hoping.
