### ISSUE TITLE
Linq Average() return Zero

### ISSUE THREAD

**Issue by alberk8** [praeclarum/sqlite-net#575]
Hi,
I have the following query that works (return the average value) on (https://github.com/oysteinkrog/SQLite.Net-PCL) but when I replace it with this package it is now not working.  Is this a bug ?

` _conn.Table<ProductPurchase>().Where(x => x.startdatetime >= _startdate && x.enddatetime <= _enddate).Select(s => s.quantityy).Average();`

**Comment by Dominaezzz** [comment]
The problem here is at this line of code [Select()](https://github.com/praeclarum/sqlite-net/blob/master/src/SQLite.cs#L2901).
The select is overridden by the class but not implemented, so if your select returns any Type that isn't the original type, it returns the default value of the returned type.
So as a temporary fix you could do this instead.
`_conn.Table<ProductPurchase>().Where(x => x.startdatetime >= _startdate && x.enddatetime <= _enddate).Average(s => s.quantityy);`

**Comment by Dominaezzz** [comment]
Since the Average function is executed on the client side.
You could do this.

`double result = _conn.Table<ProductPurchase>().Where(x => x.startdatetime >= _startdate && x.enddatetime <= _enddate).ToList().Select(s => s.quantity).DefaultIfEmpty(0).Average();`

Since Average crashes on empty collections, use DefaultIfEmpty to fix that.
To prevent creating a new object for only on property, use Select to extract that single column/property.
Since Select doesn't work because of the bug, I use the default Select by LINQ by using ToList() which brings everything to the client side.

**Comment by alberk8** [comment]
Thanks for the detailed explanation.  Is the Select() Bug going to be fixed soon?  Thank you.

**Comment by Dominaezzz** [comment]
I cannot say for sure if there is even a plan to fix it soon.
It can be easily fixed by commenting out/removing the Select() function.
I can't be bothered to open a pull request.
I am working on an SQLite ORM myself, with more features. I might release it soon.

**Comment by praeclarum** [comment]
Ahh good catch. I'll work on a fix!
