### ISSUE TITLE
IgnoreAttribute not working

### ISSUE THREAD

**Issue by blimkemann** [praeclarum/sqlite-net#586]
I have a base class that includes [Ignore] on a couple of properties. I am calling CreateTable on a derived class and the ignored properties in the base class are not being ignored.

Example:

``` csharp
public class BaseClass
{
  [Ignore]
  public string ToIgnore
  {
    get;
    set;
  }
}

public class TableClass : BaseClass
{
  public string Name { get; set; }
}
```
Calling CreateTable&lt;TableClass&gt; creates a table with Name AND ToIgnore!

This is in a NetStandard project.

A fix involves modifying the TableMapping method as follows:

```csharp
var cols = new List&lt;Column&gt; ();
			foreach (var p in props) {
				var ignore = p.GetCustomAttribute&lt;IgnoreAttribute&gt;(); //p.IsDefined(typeof(IgnoreAttribute),true);
				if (p.CanWrite && ignore==null) { //!ignore) {
					cols.Add (new Column (p, createFlags));
				}
			}
```

**Comment by praeclarum** [comment]
Oh thanks for catching that. Have to check the tests to see why this wasn't caught.

I thought `p.IsDefined(typeof(IgnoreAttribute),true);` was enough...

**Comment by praeclarum** [comment]
I can't repro the bug -- `IsDefined(..., true)` works.

Which version of .NET are you running this on?

**Comment by blimkemann** [comment]
The code I have the database initialization in is NetStandard 1.4 and I was running it via a UWP Xamarin Forms app.

**Comment by hvaughan3** [comment]
@praeclarum @blimkemann 
Possibly related to my [post here](https://github.com/praeclarum/sqlite-net/issues/549#issuecomment-315137240)?

**Comment by blimkemann** [comment]
I think it is the same issue.

**Comment by praeclarum** [comment]
Here is the test code I wrote: https://github.com/praeclarum/sqlite-net/blob/master/tests/IgnoreTest.cs#L95-L126

```csharp
		public class BaseClass
		{
			[Ignore]
			public string ToIgnore {
				get;
				set;
			}
		}

		public class TableClass : BaseClass
		{
			public string Name { get; set; }
		}

		[Test]
		public void BaseIgnores ()
		{
			var db = new TestDb ();
			db.CreateTable<TableClass> ();

			var o = new TableClass {
				ToIgnore = "Hello",
				Name = "World",
			};

			db.Insert (o);

			var oo = db.Table<TableClass> ().First ();

			Assert.AreEqual (null, oo.ToIgnore);
			Assert.AreEqual ("World", oo.Name);
		}
```

The test passes. Is your code different?

**Comment by blimkemann** [comment]
Have you run this test from a netstandard project that is referenced by UWP? That is my particular environment (haven’t tried other platforms yet) and I’m wondering if it’s a UWP / NetStandard issue?

**Comment by hvaughan3** [comment]
A test case for my specific issue would look like this (though I have not actually tried running the following code myself):

public class BaseClass
		{
			public List<string> ToIgnore {
				get;
				set;
			}
		}

		public class TableClass : BaseClass
		{
                        [Ignore]
			public List<string> ToIgnore {
				get;
				set;
			}
		}

When it tries to create `TableClass` table it will ignore the `[Ignore]` attribute in the derived class.

**Comment by praeclarum** [comment]
OK, that's a bit different than the test (you would need the `new` keyword FYI). I'll try that out.

**Comment by shawnmurtagh** [comment]
Following up on what was last mentioned by @hvaughan3 :

When sqlite-net created a database instance with the `SQLiteConnection` constructor for the following `SqliteAnimal` model, it didn't ignore the overridden or new prop:
```csharp
class DomainAnimal
{
    public DomainAnimal() { }

    public int ID { get; set; }
    public virtual int Eyes { get; set; }
    public int Legs { get; set; }
}

class SqliteAnimal : DomainAnimal
{
    public SqliteAnimal()
        : base() { }

    [Ignore]
    public override int Eyes { get; set; }
    [Ignore]
    new public int Legs { get; set; }
}
```
![DB_Browser_for_SQLite_2019-04-05_14-38-16](https://user-images.githubusercontent.com/17507678/55649230-7c226400-57b0-11e9-9fb2-0be5773a407d.png)

It did however ignore the value I assigned to the `Leg` prop before inserting:
![DB_Browser_for_SQLite_2019-04-05_14-39-31](https://user-images.githubusercontent.com/17507678/55649304-aaa03f00-57b0-11e9-9505-afc469494a1f.png)

I think ignoring in the derived class would be particularly useful for consuming an outside library in a project and keeping the responsibility of sqlite attributes in the project that's actually implementing sqlite. I.e. I don't want sqlite attributes in my domain. I did a little testing with `GetMapping()` but wasn't sure what to look for to see why it wasn't being ignored. Not sure if the ignored value of `Leg` is expected behavior.
