### ISSUE TITLE
File is encrypted or is not a database

### ISSUE THREAD

**Issue by dompham** [praeclarum/sqlite-net#693]
I'm using the beta for sqlite-net-sqlcipher and when I try to open the connection then SetKey (or executing PRAGMA), I get the error in the title.  However, I can pull the file off the device and verify it is not encrypted. Furthermore, if I just remove the setkey on subsequent runs, it'll access the DB fine.  Uncommenting any of the three key lines will cause this error.

```
            var dbSql = new SQLiteConnection(folderPath + "/test.sqlite");

            //dbSql.Execute("PRAGMA Key = 'helloworld'");
            //dbSql.ExecuteScalar<string>("PRAGMA Key = 'helloworld'");
            dbSql.SetKey("helloworld");

            dbSql.CreateTable<fakesql>();
            dbSql.Insert(new fakesql());
```

**Comment by ericsink** [comment]
What platform?

**Comment by dompham** [comment]
Xamarin iOS

**Comment by ericsink** [comment]
Is this a newly created sqlite file?  I *think* it needs to be.  What happens if you change test.sqlite to a name that definitely does not exist yet?

Also, to verify what sqlite library you're actually calling,  call `dbSql.ExecuteScalar<string>("SELECT sqlite_version()");` and see what it returns.

**Comment by dompham** [comment]
3.8.10.2 and BOOM!  You are correct about the new name.  Thanks for your time!
