### ISSUE TITLE
RunInTransactionAsync obsolete

### ISSUE THREAD

**Issue by acaliaro** [praeclarum/sqlite-net#699]
Hi @praeclarum 

I would like to use RunInTransactionAsync with a SQLiteAsyncConnection but appears an "obsolete" warning". It seems I can use RunInTransactionAsync only with SQLiteConnection (not "async"). Is it correct?

Thanks
Alessandro

**Comment by Weldryn** [comment]
Yes. Using the async version of the connection could lead to a deadlock.

[Here](https://github.com/praeclarum/sqlite-net/blob/7fa6077c518a87712b55075a875b1ec0a0c9e95f/src/SQLiteAsync.cs#L247)  is the obsolete line statement

**Comment by acaliaro** [comment]
Ok, I have read it, but how can i use Transaction in a AsyncConnection? Should I not use AsyncConnection at all?

**Comment by Weldryn** [comment]
You could do something like that:

	asyncConnection.RunInTransactionAsync(nonAsyncConnection =>
	{
		foreach (var item in items)
		{
			nonAsyncConnection.InsertOrReplace(item);
		}
	});

If you use non-async methods on the connection parameter, the compiler will not complain about the ambiguity.

Hope this helps!

**Comment by praeclarum** [comment]
@Weldryn has the right usage.

Now that I look at it, it doesn't seem so intuitive, but that's the price we're currently paying for correctness.

**Comment by danielPollackGitHub** [comment]
f

**Comment by danielPollackGitHub** [comment]
Hmm. For a xamarin application, wouldn't using the SQLiteConnection for a database synchronization activity still lock the UI. I'm just trying to avoid having the UI lock, and this seems to be doing just that.

**Comment by Weldryn** [comment]
@danielPollackGitHub
Not at all. The outer connection is asynchronous. That is why the method is
named 'RunInTransactionAsync' : it runs the commands you set inside
lambda through
a synchronous connection as an asynchronous transaction. The inner
connection used inside the transaction is the one being used asynchronously.
It does not make sense to use an asynchronous connection inside an already
asynchronous transaction.

Hope this helps !

P.S. it could freeze your UI only if you would use the 'SQLiteConnection'
in the UI context and at the same time because of the transaction. However
doing CPU intensive or I/O bound work on the UI context is most of the time
a bad idea, if you ask me...
