### ISSUE TITLE
.Net Framework v4.0 support

### ISSUE THREAD

**Issue by oleg-varlamov** [praeclarum/sqlite-net#771]
We have a project written on this platform, but I can not find any provider for SQLite that would support encryption and would work under MONO in Linux (and also on windows with .net v4.0).

We would like to know whether you plan to add support for the .net v4.0?

**Comment by ericsink** [comment]
.NET 4.0 is ancient, so you'll probably have to take responsibility for extra work to make this happen.

sqlite-net can use SQLitePCL.raw as its lower layer.

I don't know if sqlite-net can support .NET 4.0, but SQLitePCL.raw can.  That said, SQLitePCL.raw presents an API that most people find unfriendly.

If you prefer the sqlite-net sort of API, and if the sql-net nuget is not claiming support for .NET 4.0, I think your best bet is probably to use sqlite-net in source form (SQLite.cs) instead of the nuget.

**Comment by oleg-varlamov** [comment]
Thank you! Source file successfully ported to .net4.0
