### ISSUE TITLE
Deployment issues when using Linux with x86 and ARM

### ISSUE THREAD

**Issue by bpiepiora** [praeclarum/sqlite-net#795]
Hi, thanks for the nice project! It helped me a lot when running Sqlite on embedded architecture!

I found an issue that prevents me from overwriting the deployment of the *.so files. When you look into the `build/net35/SQLitePCLRaw.lib.e_sqlite3.linux.targets` file there is a "wrong" `/` that points to the root filesystem on Linux:

`<ItemGroup Condition=" '$(OS)' == 'Unix' AND !Exists('/Library/Frameworks') ">`

When you remove the `/` before `Library/Frameworks`, you're able to deploy the *.so files in the `Library/Frameworks` directory and add a DllMap to the config file of the application. That could be pulled by Mono, so there is no need of deploying a new version for each architecture.

**Comment by ericsink** [comment]
(Note that this issue is specific to SQLitePCL.raw, which has a separate repo at ericsink/SQLitePCL.raw)

The purpose of that check is to see if the system is a Mac, which has `/Library/Frameworks`, whereas a Linux machine would (normally) not.  The msbuild variable OS just says Unix, which doesn't distinguish between Mac and Linux.

**Comment by bpiepiora** [comment]
Okay, moving over to SQLitePCL.raw!
