### ISSUE TITLE
[Help Wanted] SQLite3 version and .Net requirement.

### ISSUE THREAD

**Issue by JimmyDeemo** [praeclarum/sqlite-net#833]
I was wondering if someone could answer the following questions for me, as I haven't been able to find the information elsewhere;

What version of sqlite is 1.5.231 built against?
Can I isolate a previous (stable) release of sqlite-net that only requires .NET 3.5? i.e. Prior to the introduction of the `Tuple` and `TypeInfo` classes, as well as the null propagating operator.
Would I be able to find out what version of sqlite like the above release was built against?

I might not be understanding the relationship between sqlite-net and the sqlite libraries, so please correct me if i'm asking the wrong questions here.

**Comment by VaslD** [comment]
From what I can gather, SQLite-Net (this library) uses [SQLitePCL.Raw](https://github.com/ericsink/SQLitePCL.raw) as provider for platform-specific SQLite. If you use default batteries (DLLs that work with SQLitePCL.raw) from [SQLitePCLRaw.bundle_green](https://www.nuget.org/packages/SQLitePCLRaw.bundle_green/), you get **e_sqlite3** on .NET Framework 3.5.

If you want to reference SQLite-Net code-only (without referencing any implicit provider), you can NuGet [SQLite-Net-Base](https://www.nuget.org/packages/sqlite-net-base/). You might want to do this when experimenting/debugging with different providers, or writing a .NET Standard library for multiple platforms. However without referencing a provider in the final app (and adding necessary *Init()*s), your app will likely crash due to some DLLNotFound exception.

**Comment by JimmyDeemo** [comment]
I'm afraid that the meaning for the original question wasn't meant to dig too deep. Unfortunately I had forgotten about the post due to no getting any answers.

In the end I used `LibVersionNumber` to find the SQLite library version number.
