### ISSUE TITLE
Xamarin.Android: System.DllNotFoundException in v1.7.302-beta

### ISSUE THREAD

**Issue by tipa** [praeclarum/sqlite-net#882]
`System.DllNotFoundException:** 'e_sqlite3 assembly:<unknown assembly> type:<unknown type> member:(null)'`
Seems like a needed dependency isn't pulled correctly. Adding `SQLitePCLRaw.lib.e_sqlite3.android` package manually fixed the issue

sqlite-net-pcl 1.7.302-beta
Xamarin 16.3.0.274
Xamarin.Android 10.0.0.43

**Comment by kyle-john** [comment]
Same issue here

**Comment by ericsink** [comment]
A new prerelease of SQLitePCLRaw is available with a fix for this problem.

The version is 2.0.2-pre20191018090318.

See over in the other issue for more details: ericsink/SQLitePCL.raw#299

Please try 2.0.2-pre20191018090318 and let us know if it fixes the problem.

Thanks!

**Comment by AntvissMedia** [comment]
> SQLitePCLRaw

I can confirm this solves the issue (tried it in three projects with 2 different configurations). Thank you!

**Comment by AntvissMedia** [comment]
@ericsink 
I can confirm this solves this issue. Tried it in 3 different projects. Thank you!

**Comment by vividos** [comment]
@ericsink I ran in to this problen and have a follow-up question. Previous versions of sqlite-net-pcl, e.g. 1.5.231, didn't need to additionally reference the package SQLitePCLRaw.lib.e_sqlite3.android in the Xamarin.Android project. Now when upgrading to 1.7.302-beta we also need this package in version 2.0.2, because the sqlite-net-pcl only references the 2.0.1 package, right?

I guess then we would need to have a new sqlite-net-pcl with upgraded reference to the SQLitePCLRaw 2.0.2 package?

**Comment by ericsink** [comment]
I'm a bit confused by your question.

sqlite-net-pcl 1.5.231 depends on SQLitePCLRaw 1.x

sqlite-net-pcl 1.7.302-beta depends on SQLitePCLRaw 2.x

SQLitePCLRaw 1.x and 2.x are not compatible, so when you do the upgrade, you need to make sure you are not mixing versions of packages.

**Comment by vividos** [comment]
I previously only referenced sqlite-net-pcl and upgaded it. Then I got this issue here and fixed it by also adding SQLitePCLRaw, in the version 2.0.2. So it would be convenient to have a new sqlite-net-pcl version that also references 2.0.2 (and not 2.0.1, which sqlite-net-pcl 1.7.302-beta has as reference). Do you agree?

**Comment by ericsink** [comment]
If sqlite-net-pcl 1.7.302-beta references 2.0.1 and you update to 2.0.2, that should not be a problem.  Something else must be going on.

**Comment by vividos** [comment]
My issue is solved by adding the SQLitePCLRaw package, but I would prefer when sqlite-net-pcl would reference 2.0.2, then I (and I guess many other users) don't need to add SQLitePCLRaw package manually. I just asked if that would also be a solution. I will create a PR that updates the SQLitePCLRaw reference to 2.0.2 then. Hopefully @praeclarum then issues another beta package.
Thanks for your fast responses!

**Comment by tipa** [comment]
I think this was fixed with the latest Nuget version
